import { ThemeProvider } from "@/components/ThemeProvider"
import { SidebarProvider } from "@/components/ui/sidebar"
import { Inter } from "next/font/google"
import { ToastContainer } from "react-toastify"

import ReactQueryProvider from "@/components/ReactQueryProvider"
import { Metadata } from "next"
import "./globals.css"

const poppins = Inter({
  subsets: ["latin"],
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "KChat",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${poppins.className}  antialiased`}>
        <ReactQueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <SidebarProvider>{children}</SidebarProvider>
            <ToastContainer limit={3} stacked />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
