import AppSidebar from "@/components/AppSidebar"
import { ThemeProvider } from "@/components/ThemeProvider"
import { SidebarProvider } from "@/components/ui/sidebar"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const poppins = Inter({
  subsets: ["latin"],
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "KChat",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${poppins.className}  antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarProvider>
            <main className="w-full">
              <AppSidebar />
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
